name = "neokta-finalizer-bot"
main = "BotFinalizeLottery.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 9 * * *"]

[[kv_namespaces]]
binding = "BOT_STATE"
id = "e6a7e9d79fac43c9bf3e46af39cfe839"
preview_id = "c5172c8114564aaa8745e4e780efa744"

[vars]
REGISTRY_ADDRESS = "0xE26d8B29d116540C7B181389D8e5a4990E41BcB5"
RPC_URL = "https://node.mainnet.etherlink.com"

HOT_SIZE = "100"
COLD_SIZE = "50"
MAX_TX = "10"
TIME_BUDGET_MS = "25000"
ATTEMPT_TTL_SEC = "600"